Rewrite (#1)
Co-authored-by: ook37 <oren+12345@taumoda.com>

diff --git a/capsfix b/capsfix
--- a/capsfix
+++ b/capsfix
@@ -1,55 +1,110 @@
 #!/usr/bin/env bash
 
-CAPSUSER="${2:-${USER:-$(whoami)}}"
-BACKUP="/home/${CAPSUSER}/.config/xkb_caps_backup"
-TMPFILE="/tmp/xkbmap"
-
-start_fix() {
-  mkdir -p "/home/${CAPSUSER}/.config"
-  touch "${TMPFILE}"
-  xkbcomp -xkb "${DISPLAY:-:0}" "${TMPFILE}" || return 1
-  if [[ ! -f "${BACKUP}" ]]; then
-    perl -0777 -ne 'print $& if /key <CAPS> {.*?};/s' "${TMPFILE}" > "${BACKUP}" && \
-    echo "Caps Lock config backed up to ${BACKUP}..."
-  fi
-  perl -0777 -i -pe 's/key <CAPS> {.*?};/key <CAPS> {\n\trepeat=no,\n\ttype[group1]="ALPHABETIC",\n\tsymbols[group1]=[ Caps_Lock, Caps_Lock],\n\tactions[group1]=[ LockMods(modifiers=Lock), Private(type=3,data[0]=1,data[1]=3,data[2]=3)]\n};/s' "${TMPFILE}" && \
-  xkbcomp -w 0 "${TMPFILE}" "${DISPLAY:-:0}" && \
-  echo "Caps Lock config switched to Mac/Windows style."
-}
-
-stop_fix() {
-  mkdir -p "/home/${CAPSUSER}/.config"
-  if [[ ! -f "${BACKUP}" ]]; then
-    echo "No backup found. Using default config..."
-    echo -e -n 'key <CAPS> {\n\ttype= "ONE_LEVEL",\n\tsymbols[Group1]= [      Caps_Lock ]\n    };' > "${BACKUP}"
-  fi
-  xkbcomp -xkb "${DISPLAY:-:0}" "${TMPFILE}" && \
-  perl -0777 -i -pe "s/key <CAPS> {[^}]*};/`cat ${BACKUP}`/s" "${TMPFILE}" && \
-  xkbcomp -w 0 "${TMPFILE}" "${DISPLAY:-:0}" && \
-  rm -f "${BACKUP}"
-  echo "Caps Lock config reverted to Linux style."
-}
-
 enable_fix() {
-  mkdir -p "/home/${CAPSUSER}/.config/autostart"
-  echo -e "[Desktop Entry]\nType=Application\nExec=/usr/bin/capsfix start\nHidden=false\nX-GNOME-Autostart-enabled=true\nName=Caps Lock State Fix\nComment=Fixes Caps Lock to work like it does on Mac and Windows" > "/home/${CAPSUSER}/.config/autostart/capsfix.desktop"
-  if start_fix; then
-    echo "Config will remain Mac/Windows style until disabled."
+  local cmd restart=0 confile="${1}"
+  cmd=("$(command -v keyd{,.rvaiya})")
+
+  if ! [[ -f ${confile} ]]; then
+    echo "#: Creating config file ${confile}..."
   else
-    rm -f "/home/${CAPSUSER}/.config/autostart/capsfix.desktop"
+    restart=1
+    echo "#: Recreating config file ${confile}..."
   fi
+
+  {
+    mkdir -p "${confile%/*}" \
+      && echo -e '[ids]\n*\n\n[main]\ncapslock = macro(capslock)\n' \
+        | tee "${confile}" &> /dev/null
+  } || {
+    echo "E: Config file creation failed!" >&2
+    exit 1
+  }
+
+  echo "#: Loading input devices..."
+  "${cmd[0]}" -m &
+  PID=$!
+  sleep 1
+  if ! ps -p "${PID}" &> /dev/null; then
+    echo "E: Loading inputs with keyd failed!" >&2
+    exit 1
+  fi
+  kill -INT "${PID}"
+  wait "${PID}"
+
+  {
+    if ! ((restart)); then
+      echo "#: Enabling keyd with systemctl..."
+      if ! systemctl is-enabled keyd &> /dev/null; then
+        systemctl enable --now keyd
+      else
+        systemctl restart keyd
+      fi
+    else
+      echo "#: Restarting keyd with systemctl..."
+      systemctl restart keyd
+    fi
+  } || {
+    echo "E: Enabling keyd with systemd failed!" >&2
+    exit 1
+  }
+
+  echo "#: Caps lock config will remain Mac/Windows style until disabled!"
 }
 
 disable_fix() {
-  rm -f "/home/${CAPSUSER}/.config/autostart/capsfix.desktop"
-  stop_fix
-  echo "Config will remain Linux style until enabled again."
+  local confile="${1}"
+
+  if ! [[ -f ${confile} ]] && ! systemctl is-enabled keyd &> /dev/null; then
+    echo "#: Nothing to do!"
+    exit 0
+  fi
+
+  if [[ -f ${confile} ]]; then
+    echo "#: Removing config file ${confile}..."
+    rm -f "${confile}"
+  fi
+
+  if systemctl is-enabled keyd &> /dev/null; then
+    echo "#: Disabling keyd with systemctl..."
+    systemctl disable --now keyd || {
+      echo "E: Disabling keyd with systemd failed!" >&2
+      exit 1
+    }
+  fi
+
+  echo "#: Caps lock config will remain Linux style until enabled again!"
 }
 
-case "${1}" in
-  enable|disable|start|stop) "${1}"_fix ;;
-  *)
-    echo "Usage: ${0##*/} {enable|disable|start|stop}"
+main() {
+  local input="${1}" err=0 config='/etc/keyd/capsfix.conf'
+
+  if ((EUID)); then
+    echo "E: capsfix must be run with sudo!" >&2
+    err=1
+  fi
+
+  if ! command -v keyd{,.rvaiya} &> /dev/null; then
+    echo "E: keyd is required to run capsfix!" >&2
+    err=1
+  fi
+
+  if ! command -v systemctl &> /dev/null; then
+    echo "E: systemd is required to run capsfix!" >&2
+    err=1
+  fi
+
+  if ((err)); then
+    echo "#: Requirements not satisified. Exiting..."
     exit 1
-    ;;
-esac
+  fi
+
+  case "${input}" in
+    enable|disable) "${1}"_fix "${config}" ;;
+    *)
+      echo "Usage: ${0##*/} {enable|disable}"
+      exit 1
+      ;;
+  esac
+}
+
+main "${1}"
